$PROVISION=<<SCRIPT
date
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define 'centos1' do |centos1|
    centos1.vm.box="jasonc/centos7"
    centos1.vm.hostname="centos1"
    centos1.vm.network "private_network", ip: "192.168.130.10"
    centos1.vm.provider :virtualbox do |vb|
      vb.name="centos1"
    end
    centos1.vm.provision "shell", inline: $PROVISION
  end
end
